### ISSUE TITLE
Error in GetProjectFileName function

### ISSUE THREAD

**Issue by SigleyL25** [ericaddison/ShibbyGit#1]
The debugger flags this line "_**GetProjectFileName = app.ActiveSheet.FullName**_" as the issue.  When I changed it to  dot **_Name_** instead of dot **_FullName_**.  The app continues but I get your internal error handling below. 

* Excel 2016 version 1805 (Build 9330.2124 Click-to-Run)

**Internal Error Handler:**
                     1. Could not find VB Project associated with open file:  App is this new, unsaved document?                     
                     2.  Uh oh! Could not find VBProject associated with App

**VBA Debugger Error:**
                       Error: Run-time error '438':
                       Object doesn't support this property or method

 I will see if I can figure out what is going wrong, but just wanted to make you aware of the issues. 
 
![shibbygit_error](https://user-images.githubusercontent.com/20485791/41749283-604a1418-756a-11e8-9eab-b9391fb2fbef.PNG)

![shibbygit_error2](https://user-images.githubusercontent.com/20485791/41749335-a91af694-756a-11e8-9d66-c6b08972e18c.PNG)

**Comment by ericaddison** [comment]
Was this fixed by #2?

**Comment by SigleyL25** [comment]
Yes, This fixed the 438 runtime error.
